version: '3'
services:
  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./docker/conf/postgres/:/docker-entrypoint-initdb.d/
    networks:
      - bezkoder

  app:
    build: BezKoder
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - POSTGRES_DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - POSTGRES_DB_USER=${POSTGRES_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - bezkoder

networks:
  bezkoder:
    driver: bridge
