global:
  scrape_interval: 120s
  evaluation_interval: 120s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/actuator/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['prometheus:9090', 'app:8080', 'prometheus:9100', 'prometheus:9113']
        labels:
          application: "BezKoder Application Metrics"

  - job_name: 'BezKoder Application Input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['app:8080']
        labels:
          application: "BezKoder Application Prometheus"
  
  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx:80']
        labels:
          application: "Nginx Loadf Balancer"

