version: '3'
services:
  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./conf/postgres/:/docker-entrypoint-initdb.d/
    networks:
      - backend

  app:
    build: BezKoder
    image: bezkoder-app
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./logs/bezkoder:/var/log/bezkoder
    env_file:
      - .env
    environment:
      - POSTGRES_DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - POSTGRES_DB_USER=${DB_USER}
      - POSTGRES_DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - backend
