version: "3"

networks:
  frontend:
    ipam:
      config:
        - subnet: 192.168.1.0/24
  backend:
    ipam:
      config:
        - subnet: 192.168.2.0/24
  monitoring:
    ipam:
      config:
        - subnet: 192.168.3.0/24
