version: '3'

networks:
  backend:
    external: true
  monitoring:
    external: true
  frontend:
    external: true

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - backend
      - frontend
      - monitoring