version: "3.4"

networks:
  monitoring:
    external: true

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./conf/loki/loki.yaml:/etc/config/loki.yaml
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - monitoring
    
    

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    user: root
    volumes:
      - /home/muhtar/nginx-reverse-proxy/logs/bezkoder:/var/log/test
      - /home/muhtar/nginx-reverse-proxy/logs/nginx:/var/log/nginx
      - /var/log/system.log:/var/log/root/system.log
      - ./conf/promtail/promtail.yaml:/etc/config/promtail-local-config.yaml
    entrypoint:
      - /usr/bin/promtail
      - -config.file=/etc/config/promtail-local-config.yaml
    ports:
      - "9080:9080"
    networks:
      - monitoring